namespace: kube-system
resources:
  - https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/v0.0.7/manifest/kube-vip-cloud-controller.yaml

configMapGenerator:
  - name: kubevip
    literals:
      - range-global=192.168.1.210-192.168.1.220
    options:
      disableNameSuffixHash: true
