apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kustomize
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jonaskop-home/argocd-applications.git
        revision: HEAD
        directories:
          - path: "kustomize/*"
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: "default"
      source:
        repoURL: https://github.com/jonaskop-home/argocd-applications
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
