apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-charts
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jonaskop-home/argocd-applications.git
        revision: HEAD
        files:
          - path: "helm/*/config.yaml"
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: "default"
      sources:
        - chart: "{{chart}}"
          repoURL: "{{repository}}"
          targetRevision: "{{version}}"
          helm:
            releaseName: "{{path.basename}}"
            valueFiles:
              - $values/{{path}}/values.yaml
        - repoURL: "https://github.com/jonaskop-home/argocd-applications"
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
