namespace: cert-manager
resources:
  - cluster-issuers.yaml
patches:
  - patch: |-
      - op: replace
        path: "/spec/acme/email"
        value: 'jonas.k.sjodin@gmail.com'
    target:
      kind: ClusterIssuer
